# Q8. Give 4 ways to create DataFrame

In [47]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[4,5,6]])
print(df)
df = pd.DataFrame({
    "Name":["Rohan","Ravi","Rohit","Raju"],
    "Age":[21,20,31,19]
}, index=[101,102,103,104])
print(df)
import numpy as np
df=pd.DataFrame(np.array([[1,2,3,4],[1,2,3,4]]))
print(df)
df=pd.DataFrame([{"ID":100,"Name":"Rohan"},
                 {"ID":101,"Name":"Ravi"}])
df

   0  1  2
0  1  2  3
1  4  5  6
      Name  Age
101  Rohan   21
102   Ravi   20
103  Rohit   31
104   Raju   19
   0  1  2  3
0  1  2  3  4
1  1  2  3  4

    ID   Name
0  100  Rohan
1  101   Ravi

Create a DataFrame to store data for 10 students with following fields:
Name
Age
Semester I marks (out of 600)
Semester II marks (out of 500)
Attendance

In [48]:
df=pd.DataFrame({
"Name":["Rohan","Ravi","Ram","Raja","Raju","Rani","Rajesh","Rinku","Rushali","Raj"]
,"Age":[21,18,19,20,21,20,19,18,29,19],
"Semester1":[590,550,450,300,350,200,500,510,490,410],
"Semester2":[490,450,350,200,250,100,400,410,390,310],
"Attendance":[100,90,80,50,20,80,90,45,55,76]
})
df

      Name  Age  Semester1  Semester2  Attendance
0    Rohan   21        590        490         100
1     Ravi   18        550        450          90
2      Ram   19        450        350          80
3     Raja   20        300        200          50
4     Raju   21        350        250          20
5     Rani   20        200        100          80
6   Rajesh   19        500        400          90
7    Rinku   18        510        410          45
8  Rushali   29        490        390          55
9      Raj   19        410        310          76

Display details of students who scored more than 560 marks in Semester I.

In [49]:
df[df["Semester1"]>560]

    Name  Age  Semester1  Semester2  Attendance
0  Rohan   21        590        490         100

vDisplay details of students who scored less than 250 marks in Semester II.

In [50]:
df[df["Semester2"]<250]

   Name  Age  Semester1  Semester2  Attendance
3  Raja   20        300        200          50
5  Rani   20        200        100          80

In [51]:
df.sort_values(by="Semester2").head(1)

   Name  Age  Semester1  Semester2  Attendance
5  Rani   20        200        100          80

Display details of student who scored maximum marks in Semester II.

In [52]:
df.sort_values(by="Semester2" ,ascending=False).head(1)

    Name  Age  Semester1  Semester2  Attendance
0  Rohan   21        590        490         100

Display details of students whose attendance is more than 75.

In [53]:
df[df["Attendance"]>75]

     Name  Age  Semester1  Semester2  Attendance
0   Rohan   21        590        490         100
1    Ravi   18        550        450          90
2     Ram   19        450        350          80
5    Rani   20        200        100          80
6  Rajesh   19        500        400          90
9     Raj   19        410        310          76

Display details of students whose attendance is less than 50.

In [54]:
df[df["Attendance"]<50]

    Name  Age  Semester1  Semester2  Attendance
4   Raju   21        350        250          20
7  Rinku   18        510        410          45

Insert 2 new records in DataFrame.

In [58]:
d=pd.DataFrame({
"Name":["Ramesh","Rakesh"],
"Age":[21,18],
"Semester1":[590,550],
"Semester2":[490,450],
"Attendance":[100,90]
})
df = pd.concat([df, d], ignore_index=True)
df

       Name  Age  Semester1  Semester2  Attendance
0     Rohan   21        590        490         100
1      Ravi   18        550        450          90
2       Ram   19        450        350          80
3      Raja   20        300        200          50
4      Raju   21        350        250          20
5      Rani   20        200        100          80
6    Rajesh   19        500        400          90
7     Rinku   18        510        410          45
8   Rushali   29        490        390          55
9       Raj   19        410        310          76
10   Ramesh   21        590        490         100
11   Rakesh   18        550        450          90
12   Ramesh   21        590        490         100
13   Rakesh   18        550        450          90

Add a new column for percentage of marks of both semesters.

In [61]:
df["percentage"]=(df["Semester1"]+df["Semester2"])/11
df

       Name  Age  Semester1  Semester2  Attendance  percentage
0     Rohan   21        590        490         100   98.181818
1      Ravi   18        550        450          90   90.909091
2       Ram   19        450        350          80   72.727273
3      Raja   20        300        200          50   45.454545
4      Raju   21        350        250          20   54.545455
5      Rani   20        200        100          80   27.272727
6    Rajesh   19        500        400          90   81.818182
7     Rinku   18        510        410          45   83.636364
8   Rushali   29        490        390          55   80.000000
9       Raj   19        410        310          76   65.454545
10   Ramesh   21        590        490         100   98.181818
11   Rakesh   18        550        450          90   90.909091
12   Ramesh   21        590        490         100   98.181818
13   Rakesh   18        550        450          90   90.909091

Add a new column for grades based on percentage:


Percentage	Grade
≥ 90	O
≥ 75 to < 90	A+
≥ 60 to < 75	A
≥ 50 to < 60	B+
≥ 40 to < 50	B
< 40	F

In [64]:
def gradefun(p):
    if p >= 90:
        return "O"
    elif p >= 75:
        return "A+"
    elif p >= 60:
        return "A"
    elif p >= 50:
        return "B+"
    elif p >= 40:
        return "B"
    else:
        return "F"
df["Grade"]=df["percentage"].apply(gradefun)
df

       Name  Age  Semester1  Semester2  Attendance  percentage Grade
0     Rohan   21        590        490         100   98.181818     O
1      Ravi   18        550        450          90   90.909091     O
2       Ram   19        450        350          80   72.727273     A
3      Raja   20        300        200          50   45.454545     B
4      Raju   21        350        250          20   54.545455    B+
5      Rani   20        200        100          80   27.272727     F
6    Rajesh   19        500        400          90   81.818182    A+
7     Rinku   18        510        410          45   83.636364    A+
8   Rushali   29        490        390          55   80.000000    A+
9       Raj   19        410        310          76   65.454545     A
10   Ramesh   21        590        490         100   98.181818     O
11   Rakesh   18        550        450          90   90.909091     O
12   Ramesh   21        590        490         100   98.181818     O
13   Rakesh   18        550        450          90   90.909091     O