Q9. Create the following DataFrame Sales containing year-wise sales figures for five salespersons in INR.
Use the years as column labels and salesperson names as row labels.

	2014	2015	2016	2017

Madhu	100.5	12000	20000	50000

Kusum	150.8	18000	50000	60000

Kinshuk	200.9	22000	70000	70000

Ankit	30000	30000	10000	80000

Shruti	40000	45000	12500	90000

In [7]:
import pandas as pd
Sales=pd.DataFrame({2014:[100.5,150.8,200.9,3000,40000],
                  2015:[12000,18000,22000,30000,45000] ,
                  2016:[20000,50000,70000,10000,12500],
                  2017:[50000,60000,70000,80000,90000]

},index=["Madhu","Kusum","Kinshuk","Ankit","Shruti"])
Sales

            2014   2015   2016   2017
Madhu      100.5  12000  20000  50000
Kusum      150.8  18000  50000  60000
Kinshuk    200.9  22000  70000  70000
Ankit     3000.0  30000  10000  80000
Shruti   40000.0  45000  12500  90000


a. Display the row labels of Sales.

In [9]:
Sales.index

Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')

b. Display the column labels of Sales.

In [10]:
Sales.columns

Index([2014, 2015, 2016, 2017], dtype='int64')

c. Display the dimensions, shape, size and values of 
Sales.

In [14]:
print(Sales.ndim)
print(Sales.shape)
print(Sales.size)
print(Sales.values)

2
(5, 4)
20
[[  100.5 12000.  20000.  50000. ]
 [  150.8 18000.  50000.  60000. ]
 [  200.9 22000.  70000.  70000. ]
 [ 3000.  30000.  10000.  80000. ]
 [40000.  45000.  12500.  90000. ]]

d. Display the last two rows of Sales.

In [15]:
Sales.tail(2)

           2014   2015   2016   2017
Ankit    3000.0  30000  10000  80000
Shruti  40000.0  45000  12500  90000

e. Display the first two columns of Sales.

In [16]:
Sales.head(2)

        2014   2015   2016   2017
Madhu  100.5  12000  20000  50000
Kusum  150.8  18000  50000  60000

f. Change the DataFrame Sales such that it becomes 
its transpose.

In [21]:
Sales=Sales.T
Sales

        Madhu    Kusum  Kinshuk    Ankit   Shruti
2014    100.5    150.8    200.9   3000.0  40000.0
2015  12000.0  18000.0  22000.0  30000.0  45000.0
2016  20000.0  50000.0  70000.0  10000.0  12500.0
2017  50000.0  60000.0  70000.0  80000.0  90000.0

g. Add data to Sales for salesman Sumeet where the 
sales made are
[196.2, 37800, 52000, 78438] in the years [2014, 
2015, 2016, 2017] respectively.

In [22]:
Sales["Sumeet"] = [196.2, 37800, 52000, 78438]
print(Sales)

        Madhu    Kusum  Kinshuk    Ankit   Shruti   Sumeet
2014    100.5    150.8    200.9   3000.0  40000.0    196.2
2015  12000.0  18000.0  22000.0  30000.0  45000.0  37800.0
2016  20000.0  50000.0  70000.0  10000.0  12500.0  52000.0
2017  50000.0  60000.0  70000.0  80000.0  90000.0  78438.0


h. Delete the data for the year 2014 from the DataFrame Sales.

In [27]:
Sales.drop(2014)

        Madhu    Kusum  Kinshuk    Ankit   Shruti   Sumeet
2015  12000.0  18000.0  22000.0  30000.0  45000.0  37800.0
2016  20000.0  50000.0  70000.0  10000.0  12500.0  52000.0
2017  50000.0  60000.0  70000.0  80000.0  90000.0  78438.0

i. Update the sale made by Shruti in 2017 to 100000.

In [30]:
Sales.loc[2017,"Shruti"]=10000
Sales

        Madhu    Kusum  Kinshuk    Ankit   Shruti   Sumeet
2014    100.5    150.8    200.9   3000.0  40000.0    196.2
2015  12000.0  18000.0  22000.0  30000.0  45000.0  37800.0
2016  20000.0  50000.0  70000.0  10000.0  12500.0  52000.0
2017  50000.0  60000.0  70000.0  80000.0  10000.0  78438.0

j. Write the values of DataFrame Sales to a 
comma-separated file SalesFigures.csv on the disk. Do 
not write the row labels and column labels.

In [32]:
Sales.to_csv("SalesFigures.csv",index=False,header=False)

k. Change the name of the salesperson Ankit to Vivaan 
and Kinshuk to Shailesh.

In [37]:
Sales=Sales.rename(columns={"Ankit":"Vivaan","Kinshuk":"Shailesh"})
Sales

        Madhu    Kusum  Shailesh   Vivaan   Shruti   Sumeet
2014    100.5    150.8     200.9   3000.0  40000.0    196.2
2015  12000.0  18000.0   22000.0  30000.0  45000.0  37800.0
2016  20000.0  50000.0   70000.0  10000.0  12500.0  52000.0
2017  50000.0  60000.0   70000.0  80000.0  10000.0  78438.0

l. Delete the data for salesman Madhu from the 
DataFrame Sales.

In [40]:
Sales.drop(columns=["Madhu"])

        Kusum  Shailesh   Vivaan   Shruti   Sumeet
2014    150.8     200.9   3000.0  40000.0    196.2
2015  18000.0   22000.0  30000.0  45000.0  37800.0
2016  50000.0   70000.0  10000.0  12500.0  52000.0
2017  60000.0   70000.0  80000.0  10000.0  78438.0